---
- name: Notepad++ Playbook
  hosts: demowin

  tasks:
  - name: Install Notepad++
    win_package:
        state: present 
        path: http://192.168.20.2/software/Don-Ho/NotepadPlusPlus/npp.7.8.6.Installer.x64.exe
        arguments: /S
        product_id: Notepad++
        creates_path: C:\Program Files\Notepad++\notepad++.exe
